<?php
$modversion['name'] = _MI_IPBOARD_NAME;
$modversion['version'] = "1.4J";
$modversion['description'] = _MI_IPBOARD_DESC;
$modversion['credits'] = "Made by<br>Koudanshi<br>( http://bbpixel.com/ )";
$modversion['author'] = "Koudanshi";
$modversion['help'] = "None";
$modversion['license'] = "Please read the licence carefully, IPB 1.3 original is not a open source and IPS, Inc don't have any responsible for bugs occurs when you use this module";
$modversion['official'] = 0;
$modversion['image'] = "html/sys-img/logo_ipbm.gif";
$modversion['dirname'] = "ipboard";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
$modversion['dropsqlfile']['mysql'] = "sql/dropmysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "ipb_admin_logs";
$modversion['tables'][1] = "ipb_admin_sessions";
$modversion['tables'][2] = "ipb_badwords";
$modversion['tables'][3] = "ipb_cache_store";
$modversion['tables'][4] = "ipb_calendar_events";
$modversion['tables'][5] = "ipb_categories";
$modversion['tables'][6] = "ipb_contacts";
$modversion['tables'][7] = "ipb_css";
$modversion['tables'][8] = "ipb_email_logs";
$modversion['tables'][10] = "ipb_faq";
$modversion['tables'][11] = "ipb_forum_perms";
$modversion['tables'][12] = "ipb_forum_tracker";
$modversion['tables'][13] = "ipb_forums";
$modversion['tables'][14] = "ipb_groups";
$modversion['tables'][15] = "ipb_languages";
$modversion['tables'][16] = "ipb_macro";
$modversion['tables'][17] = "ipb_macro_name";
$modversion['tables'][18] = "ipb_member_extra";
$modversion['tables'][19] = "ipb_messages";
$modversion['tables'][20] = "ipb_moderator_logs";
$modversion['tables'][21] = "ipb_moderators";
$modversion['tables'][22] = "ipb_pfields_content";
$modversion['tables'][23] = "ipb_pfields_data";
$modversion['tables'][24] = "ipb_polls";
$modversion['tables'][25] = "ipb_posts";
$modversion['tables'][26] = "ipb_reg_antispam";
$modversion['tables'][27] = "ipb_search_results";
$modversion['tables'][28] = "ipb_skin_templates";
$modversion['tables'][29] = "ipb_skins";
$modversion['tables'][30] = "ipb_spider_logs";
$modversion['tables'][31] = "ipb_stats";
$modversion['tables'][32] = "ipb_subscriptions";
$modversion['tables'][33] = "ipb_subscription_extra";
$modversion['tables'][34] = "ipb_subscription_trans";
$modversion['tables'][35] = "ipb_subscription_logs";
$modversion['tables'][36] = "ipb_subscription_methods";
$modversion['tables'][37] = "ipb_subscription_currency";
$modversion['tables'][38] = "ipb_templates";
$modversion['tables'][39] = "ipb_titles";
$modversion['tables'][40] = "ipb_tmpl_names";
$modversion['tables'][41] = "ipb_topic_mmod";
$modversion['tables'][42] = "ipb_topics";
$modversion['tables'][43] = "ipb_tracker";
$modversion['tables'][44] = "ipb_validating";
$modversion['tables'][45] = "ipb_voters";
$modversion['tables'][46] = "ipb_warn_logs";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "index.php";
$modversion['adminmenu'] = "menu.php";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "search.inc.php";
$modversion['search']['func'] = "ipboard_search";

// Menu
$modversion['hasMain'] = 1;

// Blocks
$modversion['blocks'][1]['file'] = "ipboard.php";
$modversion['blocks'][1]['name'] = _MI_IPBOARD_BNAME1;
$modversion['blocks'][1]['description'] = "Shows recent topics in the forums";
$modversion['blocks'][1]['show_func'] = "ipboard_topics_show";
$modversion['blocks'][1]['options'] = "10|1|time";
$modversion['blocks'][1]['edit_func'] = "ipboard_topics_edit";
$modversion['blocks'][1]['template'] = 'ipboard_block_new.html';

$modversion['blocks'][2]['file'] = "ipboard.php";
$modversion['blocks'][2]['name'] = _MI_IPBOARD_BNAME2;
$modversion['blocks'][2]['description'] = "Shows most viewed topics in the forums";
$modversion['blocks'][2]['show_func'] = "ipboard_topics_show";
$modversion['blocks'][2]['options'] = "10|1|views";
$modversion['blocks'][2]['edit_func'] = "ipboard_topics_edit";
$modversion['blocks'][2]['template'] = 'ipboard_block_top.html';

$modversion['blocks'][3]['file'] = "ipboard.php";
$modversion['blocks'][3]['name'] = _MI_IPBOARD_BNAME3;
$modversion['blocks'][3]['description'] = "Shows most active topics in the forums";
$modversion['blocks'][3]['show_func'] = "ipboard_topics_show";
$modversion['blocks'][3]['options'] = "10|1|replies";
$modversion['blocks'][3]['edit_func'] = "ipboard_topics_edit";
$modversion['blocks'][3]['template'] = 'ipboard_block_active.html';

$modversion['blocks'][4]['file'] = "ipboard.php";
$modversion['blocks'][4]['name'] = _MI_IPBOARD_BDAY;
$modversion['blocks'][4]['description'] = "Shows today's birthday ";
$modversion['blocks'][4]['show_func'] = "ipboard_bday_show";
$modversion['blocks'][4]['options'] = "10|1|name";
$modversion['blocks'][4]['edit_func'] = "ipboard_bday_edit";
$modversion['blocks'][4]['template'] = 'ipboard_block_bday.html';

$modversion['blocks'][5]['file'] = "ipboard.php";
$modversion['blocks'][5]['name'] = _MI_IPBOARD_WCOME;
$modversion['blocks'][5]['description'] = "Welcome Panel show as block";
$modversion['blocks'][5]['show_func'] = "ipboard_welcome_show";
$modversion['blocks'][5]['options'] = "1|1";
$modversion['blocks'][5]['edit_func'] = "ipboard_welcome_edit";
$modversion['blocks'][5]['template'] = 'ipboard_block_wcome.html';

?>